unit uPSI_u7zWrapper;

{ Initial version generated by UnitParser v0.7
}
interface

uses
  SysUtils, Classes, u7zWrapper, uPSRuntime, uPSCompiler;

{ compile-time registration functions }
procedure SIRegister_u7zWrapper(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_u7zWrapper_Routines(S: TPSExec);
procedure RIRegister_u7zWrapper(CL: TPSRuntimeClassImporter);


implementation


(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_u7zWrapper(CL: TPSPascalCompiler);
begin
  // Nop.
  // CL.AddConstantN('kw7zCacheFileExt', 'String').SetString('.txt');
  CL.AddClassN(CL.FindClass('TOBJECT'), 'w7zException');
  CL.AddDelphiFunction(
    'Procedure w7zListFiles(const aFilename: string; PackedFiles: TStrings; const OnlyPaths: boolean; const UseCache: boolean; const Password: string)');
  CL.AddDelphiFunction(
    'Function w7zExtractFile(const a7zArchive: string; const aFileMask: string; aFolder: string; const ShowProgress: boolean; const Password: string) : integer');
  CL.AddDelphiFunction(
    'Function w7zCompressFile(const a7zArchive: string; aFileList: TStrings; const ShowProgress: boolean; const CompType: string) : integer');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_u7zWrapper_Routines(S: TPSExec);
begin
  S.RegisterDelphiFunction(@w7zListFiles, 'w7zListFiles', cdRegister);
  S.RegisterDelphiFunction(@w7zExtractFile, 'w7zExtractFile', cdRegister);
  S.RegisterDelphiFunction(@w7zCompressFile, 'w7zCompressFile', cdRegister);
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_u7zWrapper(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(w7zException) do ;
end;


end.
